database:
  host: localhost
  port: 5001  
  name: registry
email:
  defaultMailFrom: '"ISA-Group" <no-reply@isa.us.es>'
  mailerApiKey: this API key has been revoked. Pass it as an environment var to
    avoid public disclosure
  messages:
    reloadAgreement:
      mailContent:
        El cálculo de SLAs para el contrato <b>%s</b> ha sido actualizado
        en base a la información cargada en los logs. <p>Número actual de registros
        que se han tenido en cuenta para realizar los cálculos:</p>
      mailSubject: "[Governify] Su tarea ha finalizado"
errors:
  progressiveTrace: false
log:
  file: "./logs/dev-logs.log"
  level: debug
  maxFiles: 30
  maxSize: 10000000
telemetry:
  enabled: false
  server: localhost:8200
maxAttempts: 10
models:
  template:
    name: TemplateModel
    path: "./src/models/templateModel.json"
    indexableParams: { id: 1 }
  agreement:
    name: AgreementModel
    path: "./src/models/agreementModel.json"
  state:
    name: StateModel
    path: "./src/models/stateModel.json"
  overrides:
    name: OverridesModel
    path: "./src/models/overridesModel.json"
  bills:
    name: BillsModel
    path: "./src/models/billsModel.json"
parallelProcess:
  guarantees: false
  metrics: false
retryDelay: 2000
server:
  port: 5400
  timeout: 86400000
  bodySize: 50mb
  bypassCORS: true
  useHelmet: true
  httpOptionsOK: true
  servePackageInfo: true
  listenOnHttps: false
  apiVersion: 6
statusBouncer: false
streaming: true
