---
production:
  database:
    host: {{DB_HOST}}{{^DB_HOST}}mongo_registry{{/DB_HOST}}
    port: {{DB_PORT}}{{^DB_PORT}}27017{{/DB_PORT}}
    name: {{DB_NAME}}{{^DB_NAME}}registry{{/DB_NAME}}
  email:
    defaultMailFrom: '"ISA-Group" <no-reply@isa.us.es>'
    mailerApiKey: this API key has been revoked. Pass it as an environment var to
      avoid public disclosure
    messages:
      reloadAgreement:
        mailContent: El cálculo de SLAs para el contrato <b>%s</b> ha sido actualizado
          en base a la información cargada en los logs. <p>Estado actual de los logs:</p>
        mailSubject: "[Governify] Su tarea ha finalizado"
  errors:
    progressiveTrace: false
  log:
    file: "./logs/prod-logs.log"
    level: debug
    maxFiles: 10
    maxSize: 10000000
  telemetry:
    enabled: false
  maxAttempts: 20
  models:
    agreement:
      name: AgreementModel
      path: "./src/models/agreementModel.json"
    state:
      name: StateModel
      path: "./src/models/stateModel.json"
    overrides:
      name: OverridesModel
      path: "./src/models/overridesModel.json"
    bills:
      name: BillsModel
      path: "./src/models/billsModel.json"
  parallelProcess:
    guarantees: false
    metrics: false
  retryDelay: 5000
  server:
    port: 80
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: false
    useHelmet: false
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
  statusBouncer: false
  streaming: true
development:
  database:
    host: localhost
    port: 37019
    name:  registry
  email:
    defaultMailFrom: '"ISA-Group" <no-reply@isa.us.es>'
    mailerApiKey: this API key has been revoked. Pass it as an environment var to
      avoid public disclosure
    messages:
      reloadAgreement:
        mailContent: El cálculo de SLAs para el contrato <b>%s</b> ha sido actualizado
          en base a la información cargada en los logs. <p>Número actual de registros
          que se han tenido en cuenta para realizar los cálculos:</p>
        mailSubject: "[Governify] Su tarea ha finalizado"
  errors:
    progressiveTrace: false
  log:
    file: "./logs/dev-logs.log"
    level: debug
    maxFiles: 30
    maxSize: 10000000
  telemetry:
    enabled: false
  maxAttempts: 10
  models:
    agreement:
      name: AgreementModel
      path: "./src/models/agreementModel.json"
    state:
      name: StateModel
      path: "./src/models/stateModel.json"
    overrides:
      name: OverridesModel
      path: "./src/models/overridesModel.json"
    bills:
      name: BillsModel
      path: "./src/models/billsModel.json"
  parallelProcess:
    guarantees: false
    metrics: false
  retryDelay: 2000
  server:
    port: 8081
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: true
    useHelmet: true
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
  statusBouncer: false
  streaming: true
testing:
  database:
    host: localhost
    port: 37019
    name:  registry
  email:
    defaultMailFrom: '"ISA-Group" <no-reply@isa.us.es>'
    mailerApiKey: this API key has been revoked. Pass it as an environment var to
      avoid public disclosure
    messages:
      reloadAgreement:
        mailContent: El cálculo de SLAs para el contrato <b>%s</b> ha sido actualizado
          en base a la información cargada en los logs. <p>Número actual de registros
          que se han tenido en cuenta para realizar los cálculos:</p>
        mailSubject: "[Governify] Su tarea ha finalizado"
  errors:
    progressiveTrace: false
  log:
    file: "./logs/test-logs.log"
    level: debug
    maxFiles: 30
    maxSize: 10000000
  telemetry:
    enabled: false
  maxAttempts: 10
  models:
    agreement:
      name: AgreementModel
      path: "./src/models/agreementModel.json"
    state:
      name: StateModel
      path: "./src/models/stateModel.json"
    overrides:
      name: OverridesModel
      path: "./src/models/overridesModel.json"
    bills:
      name: BillsModel
      path: "./src/models/billsModel.json"
  parallelProcess:
    guarantees: false
    metrics: false
  retryDelay: 2000
  server:
    port: 8081
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: true
    useHelmet: true
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
  statusBouncer: false
  streaming: true
